language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Djavax.xml.accessExternalSchema=all -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
